language: python
python:
  - "3.6"

env:
  global:
    - DJANGO_SETTINGS_MODULE=hago.settings.local

# command to install dependencies
install:
  - pip install -U pip
  - pip install -r requirements/base.txt
  - python manage.py migrate --noinput

# command to run flake8
script:
  - flake8 ./
