language: python
python:
  - "3.6"

services:
  - postgres

env:
  global:
    - DJANGO_SETTINGS_MODULE=hago.settings.local

# command to install dependencies
install:
  - pip install -U pip
  - pip install -r requirements/base.txt
  - psql -c 'create database hago;' -U postgres
  - python manage.py migrate --noinput

# command to run flake8
script:
  - flake8 ./
